[2024-10-14T08:53:36.803+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T08:53:36.815+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-14T08:53:35.599676+00:00 [queued]>
[2024-10-14T08:53:36.820+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-14T08:53:35.599676+00:00 [queued]>
[2024-10-14T08:53:36.820+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-14T08:53:36.826+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): spark_count_number_of_accidents> on 2024-10-14 08:53:35.599676+00:00
[2024-10-14T08:53:36.830+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1133) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T08:53:36.831+0000] {standard_task_runner.py:72} INFO - Started process 1135 to run task
[2024-10-14T08:53:36.832+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'count_accidents', 'spark_count_number_of_accidents', 'manual__2024-10-14T08:53:35.599676+00:00', '--job-id', '324', '--raw', '--subdir', 'DAGS_FOLDER/count_accidents_dag.py', '--cfg-path', '/tmp/tmpanlsuxhs']
[2024-10-14T08:53:36.833+0000] {standard_task_runner.py:105} INFO - Job 324: Subtask spark_count_number_of_accidents
[2024-10-14T08:53:36.869+0000] {task_command.py:467} INFO - Running <TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-14T08:53:35.599676+00:00 [running]> on host 14eb9bd36bc1
[2024-10-14T08:53:36.920+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='count_accidents' AIRFLOW_CTX_TASK_ID='spark_count_number_of_accidents' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T08:53:35.599676+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-14T08:53:35.599676+00:00'
[2024-10-14T08:53:36.921+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-14T08:53:36.922+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-14T08:53:36.922+0000] {logging_mixin.py:190} INFO - Current task name:spark_count_number_of_accidents state:running start_date:2024-10-14 08:53:36.815895+00:00
[2024-10-14T08:53:36.922+0000] {logging_mixin.py:190} INFO - Dag name:count_accidents and current dag run status:running
[2024-10-14T08:53:36.922+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T08:53:36.928+0000] {base.py:84} INFO - Retrieving connection 'spark'
[2024-10-14T08:53:36.929+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark-submit --master :7077:7077 --name arrow-spark --queue YARN --deploy-mode client ../spark/count_accidents.py
[2024-10-14T08:53:37.883+0000] {spark_submit.py:571} INFO - python3: can't open file '/opt/spark/count_accidents.py': [Errno 2] No such file or directory
[2024-10-14T08:53:37.890+0000] {spark_submit.py:571} INFO - 24/10/14 08:53:37 INFO ShutdownHookManager: Shutdown hook called
[2024-10-14T08:53:37.891+0000] {spark_submit.py:571} INFO - 24/10/14 08:53:37 INFO ShutdownHookManager: Deleting directory /tmp/spark-cdf9fde7-0e72-49a7-90ef-32ef3aff4d19
[2024-10-14T08:53:37.912+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-submit --master :7077:7077 --name arrow-spark --queue YARN --deploy-mode client ../spark/count_accidents.py. Error code is: 2.
[2024-10-14T08:53:37.915+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-14T08:53:37.915+0000] {logging_mixin.py:190} INFO - Task start:2024-10-14 08:53:36.815895+00:00 end:2024-10-14 08:53:37.914903+00:00 duration:1.099008
[2024-10-14T08:53:37.915+0000] {logging_mixin.py:190} INFO - Task:<Task(SparkSubmitOperator): spark_count_number_of_accidents> dag:<DAG: count_accidents> dagrun:<DagRun count_accidents @ 2024-10-14 08:53:35.599676+00:00: manual__2024-10-14T08:53:35.599676+00:00, state:running, queued_at: 2024-10-14 08:53:35.608515+00:00. externally triggered: True>
[2024-10-14T08:53:37.915+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot execute: spark-submit --master spark-submit --master :7077:7077 --name arrow-spark --queue YARN --deploy-mode client ../spark/count_accidents.py. Error code is: 2.
[2024-10-14T08:53:37.916+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=count_accidents, task_id=spark_count_number_of_accidents, run_id=manual__2024-10-14T08:53:35.599676+00:00, execution_date=20241014T085335, start_date=20241014T085336, end_date=20241014T085337
[2024-10-14T08:53:37.924+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T08:53:37.924+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 324 for task spark_count_number_of_accidents (Cannot execute: spark-submit --master spark-submit --master :7077:7077 --name arrow-spark --queue YARN --deploy-mode client ../spark/count_accidents.py. Error code is: 2.; 1135)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-submit --master :7077:7077 --name arrow-spark --queue YARN --deploy-mode client ../spark/count_accidents.py. Error code is: 2.
[2024-10-14T08:53:37.961+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-14T08:53:37.974+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T08:53:37.975+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
